#!/usr/bin/env python3
"""
build_audio_manifest.py
-----------------------
Auto-wires your hymn recordings into the app.

Drop your exported recordings into  assets/audio/  named by their
Christ in Song number, e.g.:

    cis_643.mp3      (preferred)
    cis643.mp3       (also fine)
    643.mp3          (also fine)
    CIS-643.m4a      (also fine)

Then run, from your project root:

    python3 build_audio_manifest.py

It writes  audio_manifest.js  mapping each CIS number to its file. Because the
Christ in Song edition's hymn numbers ARE the CIS numbers, a recording named
cis_643 lights up CIS hymn 643 automatically — no manual editing.

SHARING ONE RECORDING ACROSS HYMNALS:
A tune can serve several hymns. To point another hymn (e.g. SDA Hymnal 499) at a
recording you already have, create a file called  audio_extra.json  next to this
script, like:

    { "499": "cis_643.mp3", "73": "cis_021.mp3" }

Those extra mappings get merged in. (The number on the left is whatever hymn
number you want the play button to appear on; the file on the right must exist
in assets/audio/.)

No pip installs needed.
"""

import json
import os
import re
import sys

AUDIO_DIR = os.path.join("assets", "audio")
EXTRA_FILE = "audio_extra.json"
OUT = "audio_manifest.js"
AUDIO_EXTS = (".mp3", ".m4a", ".aac", ".wav")

# Pulls the number out of names like cis_643, cis643, CIS-643, 643
NUM_RE = re.compile(r"(?:cis[_\-]?)?0*(\d+)", re.IGNORECASE)


def find_recordings():
    if not os.path.isdir(AUDIO_DIR):
        print(f"  No folder '{AUDIO_DIR}'. Creating it — put your recordings there.")
        os.makedirs(AUDIO_DIR, exist_ok=True)
        return {}
    mapping = {}
    for name in sorted(os.listdir(AUDIO_DIR)):
        stem, ext = os.path.splitext(name)
        if ext.lower() not in AUDIO_EXTS:
            continue
        m = NUM_RE.fullmatch(stem.strip())
        if not m:
            print(f"  ? Skipped '{name}' — couldn't read a CIS number from the name.")
            continue
        num = int(m.group(1))
        if num in mapping:
            print(f"  ! Two files map to {num}: '{mapping[num]}' and '{name}'. "
                  f"Keeping '{name}'.")
        mapping[num] = name
    return mapping


def load_extra():
    if not os.path.exists(EXTRA_FILE):
        return {}
    try:
        raw = json.load(open(EXTRA_FILE, encoding="utf-8"))
        return {int(k): v for k, v in raw.items()}
    except Exception as e:
        print(f"  ! Could not read {EXTRA_FILE} ({e}); ignoring it.")
        return {}


def main():
    found = find_recordings()
    extra = load_extra()

    # Validate extra files exist
    for num, fname in extra.items():
        if not os.path.exists(os.path.join(AUDIO_DIR, fname)):
            print(f"  ! audio_extra: file '{fname}' for hymn {num} not found in "
                  f"{AUDIO_DIR} — skipping.")
    merged = dict(found)
    for num, fname in extra.items():
        if os.path.exists(os.path.join(AUDIO_DIR, fname)):
            merged[num] = fname

    lines = [
        "// audio_manifest.js — auto-generated by build_audio_manifest.py",
        "// One line per hymn number -> recording. Re-run the script after adding files.",
        "// DO NOT hand-edit; your changes will be overwritten. Use audio_extra.json instead.",
        "export const AUDIO = {",
    ]
    for num in sorted(merged):
        fname = merged[num]
        lines.append(f"  {num}: require('./{AUDIO_DIR}/{fname}'),")
    lines.append("};")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print()
    print(f"  Wrote {OUT} with {len(merged)} recording(s) wired up:")
    for num in sorted(merged):
        print(f"    hymn {num:>4}  <-  {merged[num]}")
    if not merged:
        print("    (none yet — add files to assets/audio/ and run again)")
    print()
    print("  Restart Expo so it sees new files:  npx expo start --clear")


if __name__ == "__main__":
    print("Wiring hymn recordings into the app ...")
    main()
